### ISSUE TITLE
Master does not compile `-Werror`

### ISSUE THREAD

**Issue by gabyx** [rttrorg/rttr#98]
master does not compile due to -Werror
clang7.0 used... -> 

```
make[2]: *** [src/rttr/CMakeFiles/rttr_core.dir/constructor.cpp.o] Error 1
In file included from /Users/gabrielnuetzi/Desktop/rttr/src/rttr/../rttr/type.h:34:
In file included from /Users/gabrielnuetzi/Desktop/rttr/src/rttr/../rttr/filter_item.h:32:
/Users/gabrielnuetzi/Desktop/rttr/src/rttr/../rttr/enum_flags.h:280:13: error: private field 'm_value' is not used [-Werror,-Wunused-private-field]
    int32_t m_value;
            ^
1 error generated.
make[2]: *** [src/rttr/CMakeFiles/rttr_core.dir/method.cpp.o] Error 1
In file included from /Users/gabrielnuetzi/Desktop/rttr/src/rttr/enumeration.cpp:28:
In file included from /Users/gabrielnuetzi/Desktop/rttr/src/rttr/../rttr/enumeration.h:32:
In file included from /Users/gabrielnuetzi/Desktop/rttr/src/rttr/../rttr/type.h:34:
In file included from /Users/gabrielnuetzi/Desktop/rttr/src/rttr/../rttr/filter_item.h:32:
/Users/gabrielnuetzi/Desktop/rttr/src/rttr/../rttr/enum_flags.h:280:13: error: private field 'm_value' is not used [-Werror,-Wunused-private-field]
    int32_t m_value;
            ^
1 error generated.
make[2]: *** [src/rttr/CMakeFiles/rttr_core.dir/enumeration.cpp.o] Error 1
make[1]: *** [src/rttr/CMakeFiles/rttr_core.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by gabyx** [comment]
also 0.9.5 release : 2bca46c
too with clang 7.0

**Comment by acki-m** [comment]
But I have added `-werror` as compiler flag:
https://github.com/rttrorg/rttr/blob/master/CMake/config.cmake#L98

The current master builds with the clang versions in travis:
https://travis-ci.org/rttrorg/rttr/builds/312099689
Clang 7.0 is not even release, maybe it is a bug?
I could upgrade the compilers from 3.7 to 5.0.
Do you want to make a pull request?

**Comment by gabyx** [comment]
gcc 7.2.0 works with v0.9.5 but not with master (`-Werror`)
why not removing `Werror`, and using these only for the travis builds...?
Isnt that an option?

**Comment by acki-m** [comment]
Does this happens at your own build, where you link against RTTR?
Or is this the offical master snapshot and compiled with gcc?

**Comment by gabyx** [comment]
This is the outsource build of `git clone ... master` with gcc 7.2.0.
Werror is a good flag, and I think you are one of the few who enforces that! This is at the same time awesome and a bit frustrating since for the user it is not of much relevance :). (I know the tests are ok -> so the library has a green light for me :-), by the way awesome project!)

**Comment by acki-m** [comment]
I am happy to except a pull request, which will fix the warning. 

I have created a pull request, which uses the g++ 7.0 and there I get a lot of warnings, but I don't know atm how to fix them.
